services:
    discoveryserver:
        build:
            context: .
            dockerfile: discoverserver/Dockerfile
        ports:
            - "8761:8761"
        networks:
            - microservices-networks
    apigateway:
        build:
            context: .
            dockerfile: apigateway/Dockerfile
        ports:
            - "8080:8080"
        networks:
            - microservices-networks
        depends_on:
            - discoveryserver
networks:
  microservices-networks:
      driver: bridge